### ISSUE TITLE
Minimal CI

### ISSUE THREAD

**Issue by sameo** [confidential-containers/kbs#10]
We could start by validating the OpenAPI 3.1 description file, with `redocly lint docs/kbs.yaml`

**Comment by ariel-adam** [comment]
@sameo dude, is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by fitzthum** [comment]
Still relevant, dude.

**Comment by ariel-adam** [comment]
Cool, added it to the CoCO releases board.
What drop and priority should be put it on?

**Comment by johananl** [comment]
Whoever ends up working on this may want to make sure all features are tested. I'm seeing some GH Actions jobs already but AFAICT some features such as `coco-as-builtin-no-verifier` aren't compiled:

https://github.com/confidential-containers/kbs/blob/8ca7c4dba6a89463446f02681df4d2a37caa3baa/.github/workflows/rust.yml#L52-L62
