### ISSUE TITLE
Kubernetes operator to deploy and manage KBS

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/kbs#119]
KBS is a critical part of the CoCo stack and it'll help to have a K8s operator to deploy and manage KBS.
We already have Kubernetes [manifest](https://github.com/confidential-containers/kbs/tree/main/config/kubernetes) to deploy KBS. The next evolution to help with managing the lifecycle of KBS is to create a K8s operator.

I can help with the implementation. But also happy to guide if anyone else is interested to pick this up.

cc @Xynnn007 @surajssd  @jensfr @sameo @snir911

**Comment by surajssd** [comment]
Why do we need an operator? What's wrong with plain simple k8s configs?

Operator makes sense when we have a (k8s-native) app that needs to talk to Kuberentes API server and reconcile on changes on some k8s api objects. Where is such use case for KBS?

**Comment by bpradipt** [comment]
> Why do we need an operator? What's wrong with plain simple k8s configs?
> 
> Operator makes sense when we have a (k8s-native) app that needs to talk to Kuberentes API server and reconcile on changes on some k8s api objects. Where is such use case for KBS?

Great question @surajssd. I see KBS evolving into a k8s-native app eventually and serving different purposes and  becoming a key component of the larger confidential compute infra. Some of the use cases that we are already seeing is w.r.to having self-managed KBS service which not only serves confidential containers, but also serves VMs and entire cluster. 

Having the operator will provide easier lifecycle management, better discoverability in the ecosystem, reconfiguration of KBS and related configs (like the AS, etc) , rotating the secrets used for authenticating to KBS app etc. 

For basic deployments the manifest is fine and please note that having the operator doesn't take away the manifest based deployment option.

**Comment by surajssd** [comment]
Operator would help in managing the KBS configs natively, especially there is this ongoing effort here for defining KBS config and moving away from cmd line args: https://github.com/confidential-containers/kbs/issues/78

**Comment by bpradipt** [comment]
Initial version of the kbs operator merged. We will continue improving it. https://github.com/confidential-containers/kbs-operator/pull/1
