### ISSUE TITLE
Implement HTTPS server to support KBS protocol APIs.

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/kbs#16]
Here we need to implement HTTPS server which support KBS protocol APIs defined in the [protocol document](https://github.com/confidential-containers/kbs/blob/main/docs/kbs_attestation_protocol.md).

Now [reference-kbs](https://github.com/virtee/reference-kbs) has implemented an HTTPS server that supports KBS protocol APIs. It is located in the [virTEE](https://github.com/virtee) community and now can well support SEV pre-attestation. However, in this repo, we still need the code of the HTTPS server part, so that based on this, we can provide internal implementation designed for CoCo, better adapt our [`attestation-agent`](https://github.com/confidential-containers/attestation-agent) and [`attestation-service`](https://github.com/confidential-containers/attestation-service), and conduct CoCo runtime secret injection to support the needs of our [`image-rs`](https://github.com/confidential-containers/image-rs) and [`kata-agent`](https://github.com/confidential-containers/kata-containers/tree/main/src/agent).

**Comment by sameo** [comment]
Any favourite framework?

**Comment by jialez0** [comment]
> Any favourite framework?

I don't have much experience in Web framework choosing. If there is no special requirement, we can choose a popular framework?

**Comment by sameo** [comment]
I would suggest actix or rocket. Both bring a large amount of dependencies, but I think we're not size constrained on the KBS side.

**Comment by sameo** [comment]
I am looking at using the warp and cookie crates for that.

**Comment by jialez0** [comment]
Resolved by #19 and #24
