### ISSUE TITLE
Support broking confidential resources which `image-rs` needs.

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/kbs#17]
This generic KBS will replace `simple-kbs` and `verdictd` as the default recommended component of the CoCo solution, so it needs to support providing existing secret resources. Currently, in the confidential containers architecture, the component requesting resources from KBS through the Attestation Agent is [`image-rs`](https://github.com/confidential-containers/image-rs), so our generic KBS needs to support the provision of the following kinds of resources required by `image-rs`:

1. Container image decryption key.
2. Registry pulling policy file.
3. Container image signature verification key, including cosign and simple signing.
4. Registry authentication informations.

This work is based on #16.

**Comment by Xynnn007** [comment]
I wonder whether we have or will have an API which can be used to "registry" a resource in the KBS? Here "registry" means
* Allocate __repository__, __type__ and __tag__ for a new resource (as https://github.com/confidential-containers/kbs/blob/main/docs/kbs.yaml#L74)

If so, maybe we can flexibly add new resources in need for test and for production

**Comment by Xynnn007** [comment]
This issue could be covered by https://github.com/confidential-containers/kbs/issues/25

**Comment by jialez0** [comment]
Now cc-kbc of AA and KBS can support broking resources described in this issue, so this issue can be closed now.

As for how exactly we should handle client resources, we can discuss the improvement in detail in a new issue in the future.
