### ISSUE TITLE
Old kbs docker image in docker-compose.yml

### ISSUE THREAD

**Issue by niteeshkd** [confidential-containers/kbs#174]
When the kbs cluster is started by running 'docker compose up -d'  with the current [docker-compose.yml](https://github.com/confidential-containers/kbs/blob/main/docker-compose.yml) file,  the kbs reports the following error message.
```
user@host:~/github/kbs$ docker compose up -d

user@host:~/github/kbs$ docker logs kbs-kbs-1
error: unexpected argument '--config-file' found

tip: a similar argument exists: '--config'

Usage: kbs <--socket <SOCKET>|--timeout <TIMEOUT>|--private-key <PRIVATE_KEY>|--certificate <CERTIFICATE>|--insecure-http|--config <CONFIG>|--auth-public-key <AUTH_PUBLIC_KEY>|--insecure-api>

For more information, try '--help'.

```

**Comment by Xynnn007** [comment]
The bug was fixed as https://github.com/confidential-containers/kbs/blob/main/kbs/docker-compose.yml#L9-L11

I test locally and succeed to start.

Can this issue be closed? @niteeshkd

**Comment by niteeshkd** [comment]
Yes, please go ahead and close it. It works for me too.
