### ISSUE TITLE
rvps docker image reports missing GLIBC_2.32, GLIBC_2.33, GLIBC_2.34.

### ISSUE THREAD

**Issue by niteeshkd** [confidential-containers/kbs#178]
If  rvps is run using the docker image built using its current docker file [Dockerfile.rvps](https://github.com/confidential-containers/attestation-service/blob/main/Dockerfile.rvps), it reports the following errors.

```
user@host:~/github/kbs$ docker compose up -d
[+] Running 4/4
 Container kbs-rvps-1         Started                                                                                                                          0.0s 
 Container kbs-as-1           Started                                                                                                                          0.0s 
 Container kbs-kbs-1          Started                                                                                                                          0.0s 
 Container kbs-keyprovider-1  Started                                                                                                                          0.0s 

user@host:~/github/kbs$ docker ps
CONTAINER ID   IMAGE                                                        COMMAND                  CREATED         STATUS                                  PORTS                                           NAMES
d1516e0a9230   ghcr.io/confidential-containers/coco-keyprovider:latest      "coco_keyprovider --#"   9 seconds ago   Up 7 seconds                            0.0.0.0:50000->50000/tcp, :::50000->50000/tcp   kbs-keyprovider-1
6935b2cefce9   kbs:grpc-as                                                  "/usr/local/bin/kbs #"   9 seconds ago   Restarting (1) Less than a second ago                                                   kbs-kbs-1
1b2e09e41c21   ghcr.io/confidential-containers/attestation-service:latest   "grpc-as --socket 0.#"   9 seconds ago   Restarting (1) Less than a second ago                                                   kbs-as-1
a3717b4fa3d8   rvps:as                                                      "rvps --socket 0.0.0#"   9 seconds ago   Restarting (1) 2 seconds ago                                                            kbs-rvps-1

user@host:~/github/kbs$ docker logs kbs-rvps-1
rvps: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by rvps)
rvps: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by rvps)
rvps: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rvps)

```

**Comment by mythi** [comment]
> > The [debian libc](https://packages.debian.org/search?keywords=libc6) link indicates that the bookworm is stable and provides newer versions of GLIBC in comparison to the bullseye . I replaced debian:bullseye-slim in the docker file [Dockerfile.rvps](https://github.com/confidential-containers/attestation-service/blob/main/Dockerfile.rvps) by debian:bookworm-slim, built the docker image and ran rvps. It does not report the above problem.
> 
> Thanks for bringing up this issue. Let me fix this after handling the issue [confidential-containers/confidential-containers#169](https://github.com/confidential-containers/confidential-containers/issues/169)

v0.8.0 release is broken.

**Comment by Xynnn007** [comment]
Fixed in the https://github.com/confidential-containers/kbs/pull/216/files#diff-ae6d6b1e65aa408a268a30bbbee271a616ac2a06b8123d76757f43f8cf0d1fdaR15 .

> v0.8.0 release is broken.

I just test locally and get
```
$/home/kbs# docker logs -f 69216ec1fc14
rvps: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by rvps)
rvps: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by rvps)
rvps: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rvps)
```

We need to re-push a fixed one replace that. Let me rebuild one and push to ghcr.io to replace that with the fixed Dockerfile https://github.com/confidential-containers/kbs/pull/216/files#diff-ae6d6b1e65aa408a268a30bbbee271a616ac2a06b8123d76757f43f8cf0d1fdaR6-R18

wdyt? @fitzthum

**Comment by fidencio** [comment]
I'd prefer tagging v0.8.1, to be honest.

**Comment by Xynnn007** [comment]
Thanks for the suggestions. I put a PR in AS repo.

**Comment by niteeshkd** [comment]
> Thanks for the suggestions. I put a PR in AS repo.

Thanks a lot!

**Comment by Xynnn007** [comment]
@niteeshkd try this `docker pull ghcr.io/confidential-containers/reference-value-provider-service:v0.8.1`

I've test it locally and run normally

**Comment by niteeshkd** [comment]
> @niteeshkd try this `docker pull ghcr.io/confidential-containers/reference-value-provider-service:v0.8.1`

It works fine!
