### ISSUE TITLE
Enable e2e tests for real TEEs

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/kbs#223]
We would like to enable e2e tests on the repo for real TEE's. At moment we only use the dummy TEE to test the integration of attester + verifier components in general. We'd like to extend the coverage to the integration with real TEEs.

To do this we need to run the workflows on self-hosted runners or external CI systems. For Azure-based TEE's (`az-{snp,tdx}-vtpm`) we can use GARM, which we use in other kata + coco circumstances already. To make this work we need to provide a token scoped to the repository to CoCo's Garm instance and register a webhook secret on the kbs repo.

**Comment by Xynnn007** [comment]
To achieve this goal, two stages in my mind
1. generate the evidence inside the guest. https://github.com/confidential-containers/guest-components/pull/418 would help to provide such a tool
2. deliver the evidence to CoCo-AS. #264 can be re-used.

**Comment by mkulke** [comment]
> To achieve this goal, two stages in my mind
> 
> 1. generate the evidence inside the guest. [attester: add evidence_getter binary guest-components#418](https://github.com/confidential-containers/guest-components/pull/418) would help to provide such a tool
> 2. deliver the evidence to CoCo-AS. [Added e2e test for CoCo-AS using SNP evidence #264](https://github.com/confidential-containers/kbs/pull/264) can be re-used.

If we use a pre-generated fixture as evidence, wouldn't this just be a unit-test for a validator?

What I had in mind was simply running https://github.com/confidential-containers/kbs/blob/main/.github/workflows/kbs-e2e.yaml on a TEE-capable runner. If the test runs e.g. on a TDX worker it should work ootb (`AA_SAMPLE_ATTESTER_TEST` needs to be unset).

**Comment by Xynnn007** [comment]
> If we use a pre-generated fixture as evidence, wouldn't this just be a unit-test for a validator?

Well, I misunderstood the idea. I thought there are two different e2e test
1. for CoCo-AS. including evidence generating on real TEE, API calling and get the attestation token
2. for KBS. including performing RCAR on real TEE, and get the resource

My last comment is for 1. Anyway, we both think that the action of obtaining evidence needs to be dynamically executed on the real TEE.

**Comment by mkulke** [comment]
Ah, I see. I was looking at #264. I saw fixtures in the `tests/e2e` folder and assumed this was the idea. But if we want to run both AS and KBS e2e tests on real TEEs then this issue is the right one, it's more about the repo configuration and the workers we need.

To be able to register a self hosted runner (ephemeral or a bare-metal box) we need the following token:

<img width="552" alt="image" src="https://github.com/confidential-containers/kbs/assets/273280/29957fae-11b8-4973-9b7a-92fc2f122eb9">

For ephemeral runners, we also need to configure a webhook + secret which listens on `Workflow jobs`

**Comment by Xynnn007** [comment]
Agreed. For the runner setting, I think @fitzthum would help.

For the self-host runner, we now have a CI machine in SGX (now working for `enclave-cc` and `guest-components` )but not configured in `kbs` repo. We might use that one?

**Comment by mkulke** [comment]
yes, it can be shared. for non-ephemeral runners (like bare-metal machines) you have to pay attention to not pollute the node in your workflows, since there is no isolation and a side-effect might break another workflow

**Comment by mkulke** [comment]
Finally it needs to be restricted who can run those jobs, you don't want people executing arbitrary code on your runner, because they opened a malicious PR.

Triggering an e2e test on real TEE on `push: main` might be a good compromise. In addition we can have a label "test-e2e" that people with privileges can set on PRs. This label triggers a PR with `pull_request_target` + additional  GH logic to actually run the code from the PR.

@wainersm can you confirm? 👆

**Comment by fitzthum** [comment]
This all sounds good to me. If you need any help adding a machine to our runner pool or enabling it for this repo or whatever lmk.

There are also these security configs we can set 
<img width="810" alt="Screenshot 2023-12-29 at 12 49 14 PM" src="https://github.com/confidential-containers/kbs/assets/3345532/c261108c-17cd-403e-ae15-ef27bd64c9ab">

**Comment by mkulke** [comment]
> This all sounds good to me. If you need any help adding a machine to our runner pool or enabling it for this repo or whatever lmk.

great, thx. I'll reach out.

**Comment by Xynnn007** [comment]
Is this error related？ https://github.com/confidential-containers/kbs/actions/runs/7523718849

**Comment by mkulke** [comment]
> Is this error related？ https://github.com/confidential-containers/kbs/actions/runs/7523718849

yes, it is. There is a problem with referencing the reusable workflow.

**Comment by mkulke** [comment]
PTAL https://github.com/confidential-containers/kbs/pull/291
