### ISSUE TITLE
Launch parameter for public key/certificate

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#26]
We need to add a launch parameter for public key/certificate to enable `HTTPS`. Maybe we need a switch for `HTTPS`/`HTTP`. If `HTTPS` is enabled, a public key or a certificate is required.

**Comment by jialez0** [comment]
Agree, and this topic mentioned here before: https://github.com/confidential-containers/kbs/pull/19#discussion_r1039276957
