### ISSUE TITLE
Intel TDX 

### ISSUE THREAD

**Issue by pegahnikbakht** [confidential-containers/kbs#269]
Hi, 
I tried to run KBS and kbs-client on azure intel TDX but the platform is not detected correctly by kbs-client, it is identified as AzSnpVtpm instead of TDX:
`Json(Request { version: "0.1.0", tee: AzSnpVtpm, extra_params: "" })  `
Do you know why it happens or can you provide more information on how I can find what is the problem?

Pegah

**Comment by Xynnn007** [comment]
The platform check logic is defined in https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/attester/src/lib.rs#L80

With the defined order, it will first check if the platform is tdx, then az_tdx_vtpm. for tdx, it checks https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/attester/src/tdx/mod.rs#L16
for az_tdx_vtpm it checks https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/attester/src/az_tdx_vtpm/mod.rs#L15

By default all attesters plugins (tee platform support) are compiled into the kbs-client tool. So please check if `/dev/tdx-attest` or `/dev/tdx-guest` exists on the Azure tdx guest.

Microsoft colleagures @mkulke @jepio may provide more details for this.

**Comment by mkulke** [comment]
Hey there @pegahnikbakht The Azure TDX support is not merged yet to KBS, there is an open PR that you might want to look at:

https://github.com/confidential-containers/kbs/pull/169

The TEE heuristic used in the current HEAD is very basic. The updated dependencies in the PR, will distinguish between SNP and TDX instances on Azure.

**Comment by pegahnikbakht** [comment]
Hey @mkulke 
I get this error when trying the tests in the PR:
```
openssl genpkey -algorithm ed25519 > kbs.key
openssl pkey -in kbs.key -pubout -out kbs.pem
mkdir -p ./data/repository/one/two && \
openssl rand 16 > ./data/repository/one/two/three
start kbs
{ \
	RUST_LOG=actix-server=warn \
	/home/ubuntu/tdx/kbs/kbs/test/kbs --config-file ./data/e2e/kbs.toml \
	& echo $! > kbs.PID; \
} && \
sleep 1
thread 'main' panicked at attestation-service/rvps/src/store/local_fs/mod.rs:31:28:
Failed to create LocalFs Store.: IO error: could not acquire lock on "/opt/confidential-containers/attestation-service/reference_values/db": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
RUST_LOG=kbs_protocol=error ./client get-resource \
	 --path one/two/three \
	 | base64 -d > roundtrip_secret && \
diff ./data/repository/one/two/three roundtrip_secret
Error: get tee type failed: no supported Tee type detected.
1d0
< ߶��93�o�}Ĵrfj
\ No newline at end of file
make: *** [Makefile:102: test-bgcheck] Error 1

```
Do you have any clue?

**Comment by mkulke** [comment]
@pegahnikbakht 

Are you running this as root? the client (accessing tpm device to gather evidence) would need to run as root, and  the `Failed to create LocalFs Store.:` message indicates that maybe the kbs process is not able to write to `/opt/confidential-containers`

**Comment by pegahnikbakht** [comment]
@mkulke 
Yes I'm running this as root, but this error `Error: get tee type failed: no supported Tee type detected.` seems like it can not detect TDX, also I don't have `/dev/tdx-attest` or `/dev/tdx-guest` in my `/dev` directory. Should they be existed?

**Comment by mkulke** [comment]
@pegahnikbakht no, those devices are not present in the current Azure TDX offering, instead the report is accessed via the tpm device. If you can access this, the detection heuristic should work.

I'll replay the instruction myself, something might have broken in rebasing

**Comment by mkulke** [comment]
@pegahnikbakht I just replayed the instructions on a fresh TDX vm and the e2e-test passed for me. What you can do is turn all the `RUST_LOG` entries in `./kbs/test/Makefile` to `debug` to get more context.

this would be my shell history:

```bash
sudo su -
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
. "$HOME/.cargo/env"
wget https://go.dev/dl/go1.21.5.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
sudo apt-get update && sudo apt-get install -y build-essential
git clone https://github.com/mkulke/kbs.git -b mkulke/add-az-tdx-vtpm-tee
curl -fsSL https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
sudo apt-get update
sudo apt-get install -y     libsgx-dcap-default-qpl     libsgx-dcap-quote-verify     libsgx-dcap-quote-verify-dev     libsgx-urts     libssl-dev     libtdx-attest     libtdx-attest-dev     libtss2-dev     make     clang     protobuf-compiler     pkg-config
cat <<EOF | sudo tee /etc/sgx_default_qcnl.conf
{
  "pccs_url": "https://global.acccache.azure.net/sgx/certification/v3/",
  "use_secure_cert": true,
  "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/",
  "pccs_api_version": "3.1",
  "retry_times": 6,
  "retry_delay": 5,
  "local_pck_url": "http://169.254.169.254/metadata/THIM/sgx/certification/v3/",
  "pck_cache_expire_hours": 24,
  "verify_collateral_cache_expire_hours": 24,
  "custom_request_options": {
    "get_cert": {
      "headers": {
        "metadata": "true"
      },
      "params": {
        "api-version": "2021-07-22-preview"
      }
    }
  }
}
EOF
cd kbs/test/
sudo make install-dependencies
make bins
sudo make e2e-test
```

**Comment by pegahnikbakht** [comment]
@mkulke 
It works now, thanks for the help :)
