### ISSUE TITLE
Question: Information about project plan for hygon csv?

### ISSUE THREAD

**Issue by ZhangLimengLimeng** [confidential-containers/kbs#294]
I saw Hygon CSV in the support list of CoCo-AS, but I couldn't find it in the support lists of CoCo-KBS or CC-KBC. 
Of course, eventually KBC/KBS/AS will be unified into the same framework. 
Do CoCo-KBS and CC-KBC have any release plans for Hygon CSV?

**Comment by Xynnn007** [comment]
Overall CCKBC and KBS is in platform independent design. It will call relative TEE attester/verifier plugins to do TEE specific things, s.t. get evidence (AA/cckbc side) and verify evidence(KBS/CoCoAS side).

Current releases of CoCoAS/KBS already supports to verify hygon evidences. However we still do not have a release at cckbc/AA side, as on other platforms they will be built in a guest image which is released.

More details probably @jialez0 @baoshunfang could help

**Comment by ZhangLimengLimeng** [comment]
> Overall CCKBC and KBS is in platform independent design. It will call relative TEE attester/verifier plugins to do TEE specific things, s.t. get evidence (AA/cckbc side) and verify evidence(KBS/CoCoAS side).总体来说CCKBC和KBS是平台无关的设计。它将调用相关的 TEE 证明者/验证者插件来执行 TEE 特定的事情，s.t.获取证据（AA/cckbc 方）并验证证据（KBS/CoCoAS 方）。
> 
> Current releases of CoCoAS/KBS already supports to verify hygon evidences. However we still do not have a release at cckbc/AA side, as on other platforms they will be built in a guest image which is released.当前版本的 CoCoAS/KBS 已经支持验证 hygon 证据。然而，我们仍然没有在 cckbc/AA 方面发布，因为在其他平台上，它们将构建在已发布的来宾映像中。
> 
> More details probably @jialez0 @BaoshunFang could help更多细节可能会有所帮助

Thank you, and best wishes.
