### ISSUE TITLE
Find alternative to csv-rs `https://gitee.com/anolis/csv-rs`

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/kbs#300]
I have seen that the `csv-rs` has been source of intermittent failures. Downloading always times out: https://gitee.com/anolis/csv-rs.

Latest being: https://github.com/confidential-containers/kbs/actions/runs/7620797065/job/20756110030?pr=293

<img width="2672" alt="Screenshot 2024-01-22 at 7 59 56 PM" src="https://github.com/confidential-containers/kbs/assets/5815795/67f8abe9-c240-4e8c-8ac4-080e394b8d3d">

I think we should find an alternative to this place of hosting.

**Comment by fitzthum** [comment]
See https://github.com/confidential-containers/kbs/pull/301

**Comment by Xynnn007** [comment]
Fixed in https://github.com/confidential-containers/kbs/pull/301
