### ISSUE TITLE
Proposing Magnus Kulke as maintainer for KBS

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/kbs#303]
Magnus (@mkulke) is actively contributing to KBS both in terms of features and reviews.  I'm proposing to add Magnus as a maintainer for the KBS project.
I also created a related issue in guest-components as both goes together.. - https://github.com/confidential-containers/guest-components/issues/456

cc @fitzthum @Xynnn007

**Comment by fitzthum** [comment]
Great idea! I think @mkulke can really help the project

**Comment by Xynnn007** [comment]
Totally agree. Welcome @mkulke (though we are old faces : P)

**Comment by sameo** [comment]
💯 From me. @mkulke is indeed an old timer already, but welcome anyways!

**Comment by fitzthum** [comment]
Added!
