### ISSUE TITLE
Docker-Compose: How to launch with docker-compose between release?

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#312]
#### Background

The [docker-compose file](https://github.com/confidential-containers/kbs/blob/main/docker-compose.yml) of KBS cluster provides a good quick-up deployments to users. Every release time we will test the cluster deployment script to work correctly and then cut the release. The image references inside the docker-compose file would refer to the latest release one, like `ghcr.io/confidential-containers/key-broker-service:latest`.

However, when we use the code between releases, the docker-compose file might not work. The reason is that we might bring some changes to the code and configuration logic of the KBS/AS/RVPS, etc. The error would look like
```plaintext
[2024-01-31T05:42:53Z INFO  kbs] Using config file /etc/kbs-config.toml
[2024-01-31T05:42:53Z INFO  api_server::attestation::coco::grpc] connect to remote AS [http://as:50004]
[2024-01-31T05:42:53Z INFO  api_server] Starting HTTP server at [0.0.0.0:8080]
Error: read user public key

Caused by:
    Is a directory (os error 21)
```

This means when a user clone the latest code of `kbs` repo, the `docker-compose up -d` command would not work in most scenarios!

#### Solutions

As we now build the KBS/AS/RVPS images every time a merge-to-main happens, and the staged images will be pushed to `ghcr.io` like [kbs](https://github.com/confidential-containers/kbs/pkgs/container/staged-images%2Fkbs), [grpc-as](https://github.com/confidential-containers/kbs/pkgs/container/staged-images%2Fcoco-as-grpc), and [rvps](https://github.com/confidential-containers/attestation-service/pkgs/container/reference-value-provider-service)

We can use the staged images inside the docker-compose file.

After some discussion with @fitzthum , there might be two selections as following. I'd like to summrize them to collect ideas, and possibly, if you have better solutions please share.

1. Use one common `docker-compose.yml`. Every time we want to cut a release, the references of images would be changed to release repos, s.t. `ghcr.io/confidential-containers/key-broker-service:latest`, `ghcr.io/confidential-containers/attestation-service:latest`, `ghcr.io/confidential-containers/reference-value-provider-service:latest` and `ghcr.io/confidential-containers/coco-keyprovider:latest`. But during the releases, s.t. within development cycle, we put a PR to change the references of images to the staged ones, s.t. `docker pull ghcr.io/confidential-containers/staged-images/coco-as-grpc:latest`, `ghcr.io/confidential-containers/staged-images/kbs-grpc-as:latest`, `ghcr.io/confidential-containers/staged-images/rvps:latest`, etc. The pro is the user would never care about the docker-compose file and it will always be used to launch the cluster successfully. The con is we should put PR to change the references everytime the release happens and happened.
2. Use two `docker-compose.yml`s. One for launching the latest stable/released version of the cluster. This is the same as what we have now. The other is for launching the cluster under developement. This is a new one and aims to launch with the latest code. The pro is we do not to modify the former one frequently. The con is obviously, we need to maintain two batches of configs, launch documents, etc.

**Comment by fitzthum** [comment]
I don't have a strong preference. Number 1 is fine with me. We'll just have to remember to do it.

**Comment by portersrc** [comment]
> This means when a user clone the latest code of kbs repo, the docker-compose up -d command would not work in most scenarios!

This could be a good thing, though, depending on what you want. If you go with option 1, you're prioritizing the end user (though it also bakes in the assumption that end users want to clone kbs and use docker-compose). If you leave it as it is, you're prioritizing the developer (because the error reveals a bug, which should be fixed).

In my opinion, cloning kbs and issuing docker-compose should build and deploy the local HEAD code, which it currently does. The staging images are good and should be used by downstream tests, but I wouldn't point the HEAD's docker-compose at them. And the release process should just pick from the candidate staging image (we're not there yet).

For what it's worth, I'm not even sure if option 1 has any benefits (yet), so maybe I'm misunderstanding you. When a kbs PR is created, tests are run. When the PR is merged, the staging images are created, correct? Are there any other tests today that happen after merge but before the staging image is created? If not, then aren't HEAD and any staging images the same with respect to stability?

I would recommend against option 2.

**Comment by fitzthum** [comment]
We do build staging images on every push. I think for a release we should point the Dockerhub to the latest one of these images. We also currently build and push again when we cut a release. I think instead we should add the release tag to the latest set of staging images.

So process for release would be 

1) tag the latest staged builds as the release images (maybe push those same images somewhere else) 
2) update the dockerfile to point to these images
3) cut the release 
4) change the dockerfile back to building from source

Maybe we could do this with a script?

**Comment by fitzthum** [comment]
Ok, I have changed my mind somewhat again. After realizing that we actually have support for a [Kubernetes deployment](https://github.com/confidential-containers/kbs/tree/52bee3481c75c5db8a7a445564c1143cb0088d9e/kbs/config/kubernetes) in the repo I am thinking that we should just keep the Docker compose file pointed towards the local builds. The k8s config will always point to the images from the last release (actual tags, not latest) and the docker compose will always build from source.

This means for the release we would only have a couple of steps

1) Tag the latest staged images as the release images
2) Make a PR to update the k8s files for the new image tags
3) Tag the repo

We can make a script to do the first two things. We won't use the workflow that currently builds release images when the repo is tagged.

**Comment by fitzthum** [comment]
We followed the logic of the last comment for the v0.8.2 release. Let's close this issue for now and pick it back up for the next release if needed.
