### ISSUE TITLE
Certificate validation issue when enabling HTTPS

### ISSUE THREAD

**Issue by lmilleri** [confidential-containers/kbs#332]
I have enabled HTTPS support in KBS by providing the following attributes in the [kbs-config](https://github.com/confidential-containers/kbs/blob/main/kbs/docs/config.md):
- private_key
- certificate

Generated a self-signed 509 certificate with the command (or similar):
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=UK/L=Bristol/O=RedHat/OU=Virt/CN=lmilleri-thinkpadp1gen3.remote.csb" -nodes`

Run the kbs-client as follows:
`./kbs-client --cert-file cert.pem --url https://kbs-service:8080 config --auth-private-key ./kbs.key set-resource --resource-file dummy_data --path default/test/dummy`

The set-resource command fails when validating the certificate:
`Error: error sending request for url (https://kbs-service:8080/kbs/v0/resource/default/test/dummy): error trying to connect: invalid peer certificate: Other(CaUsedAsEndEntity)
`

Does anyone know the reason? Problem on how the certificate is generated or kbs bug?

**Comment by fitzthum** [comment]
Possibly related to https://github.com/confidential-containers/kbs/issues/47

**Comment by Xynnn007** [comment]
Hi @lmilleri , thanks for bringing this up!

I used the following steps and succeeded.

#### Generate a self-signed certificate

```bash
# Edit a crt configuration
cat << localhost.crt > EOF
[req]
default_bits       = 2048
default_keyfile    = localhost.key
distinguished_name = req_distinguished_name
req_extensions     = req_ext
x509_extensions    = v3_ca

[req_distinguished_name]
countryName                 = Country Name (2 letter code)
countryName_default         = CN
stateOrProvinceName         = State or Province Name (full name)
stateOrProvinceName_default = Zhejiang
localityName                = Locality Name (eg, city)
localityName_default        = Hangzhou
organizationName            = Organization Name (eg, company)
organizationName_default    = localhost
organizationalUnitName      = organizationalunit
organizationalUnitName_default = Development
commonName                  = Common Name (e.g. server FQDN or YOUR name)
commonName_default          = localhost
commonName_max              = 64

[req_ext]
subjectAltName = @alt_names

[v3_ca]
subjectAltName = @alt_names

[alt_names]
DNS.1   = localhost
DNS.2   = 127.0.0.1
EOF

# generate the private key and self-signed cert
openssl req -x509 -nodes -days 365 \
  -newkey rsa:2048 \
  -keyout localhost.key \
  -out localhost.crt \
  -config localhost.conf \
  -passin pass:
```
#### Generate resource retrieve key pair

```bash
openssl genpkey -algorithm ed25519 > private.key
openssl pkey -in private.key -pubout -out public.pub
```

#### Launch KBS server
Set up a `kbs-config.toml`
```bash
cat << kbs-config.toml > EOF
private_key = "/etc/key.pem"
certificate = "/etc/cert.pem"

sockets = ["0.0.0.0:8080"]

auth_public_key = "/etc/public.pub"

insecure_api = true

[attestation_token_config]
attestation_token_type = "CoCo"

[repository_config]
type = "LocalFs"
dir_path = "/opt/confidential-containers/kbs/repository"

[as_config]
work_dir = "/opt/confidential-containers/attestation-service"
policy_engine = "opa"
rvps_store_type = "LocalFs"
attestation_token_broker = "Simple"

[as_config.attestation_token_config]
duration_min = 5

[as_config.rvps_config]
store_type = "LocalFs"
remote_addr = ""

[policy_engine_config]
policy_path = "/opa/confidential-containers/kbs/policy.rego"
EOF
```

Use docker to run KBS-built-in-as
```bash
docker run -it --rm \
  -v $(pwd)/kbs-config.toml:/etc/kbs-config.toml \
  -v $(pwd)/localhost.key:/etc/key.pem \
  -v $(pwd)/localhost.crt:/etc/cert.pem \
  -v $(pwd)/public.pub:/etc/public.pub \
  --env RUST_LOG=debug \
  -p 8080:8080 \
  kbs:coco-as \
  kbs --config-file /etc/kbs-config.toml
```

`kbs:coco-as` is built from `docker build -t kbs:coco-as . -f kbs/docker/Dockerfile`, also can use a staged image from https://github.com/confidential-containers/kbs/pkgs/container/staged-images%2Fkbs

#### Use client tool to access

```bash
echo testdata > dummy_data
kbs-client --cert-file localhost.crt \
  --url https://localhost:8080 \
  config \
  --auth-private-key private.key \
  set-resource \
  --resource-file dummy_data \
  --path default/test/dummy
```

and the result 
```plaintext
Set resource success
```


Please check if this works.

**The port mapping is very important as the FQDN inside the cert is set as `localhost`.** We must ensure the URI used on the client tool set is the same as the one inside the certificate's CommonName.

**Comment by lmilleri** [comment]
You're right, it was a problem when generating the certificate. Thanks a lot!
