### ISSUE TITLE
Q: Would a JSON (yaml/toml)-backed RVPS store make sense?

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/kbs#338]
At the moment we rely on an embedded database (sled) to store reference values, that makes a kbs/rvps deployment stateful, which is operationally challenging (think replication). Maybe it makes sense to have the option to provide a flat file store (can be read-only maybe?)  for rvps, so it can be backed by k8s configmaps or similar mechanisms.

**Comment by Xynnn007** [comment]
Makes sense.

**Comment by Xynnn007** [comment]
Let me do this. I think this could help delete useless imports before RVPS becomes mature.

**Comment by mkulke** [comment]
I used this impl for my debugging purposes, we might want to make the path configurable:

https://github.com/mkulke/kbs/commit/3b7244c47a15dc870a4b46ca13edc76a92e0e5ff

**Comment by bpradipt** [comment]
Using configmaps to store the data make sense to me. 
A related question is do we expect RVPS to have a huge number of references (beyond configmap limit)? That might require a rethink.

**Comment by mkulke** [comment]
> Using configmaps to store the data make sense to me. A related question is do we expect RVPS to have a huge number of references (beyond configmap limit)? That might require a rethink.

rvps has a relatively simple "store" interface. pretty much get/set, so there could be many storage backends
