### ISSUE TITLE
[support] Is there any end-to-end demo of attestation based on KBS and AS?

### ISSUE THREAD

**Issue by chendave** [confidential-containers/kbs#36]
Hi there, 

I have been read the code for a few days, but I am unable to find an end-to-end demo to show the whole process for attestation? e.g. How the payload of http URL is looks like? either `sample` or `tdx` verifier` should be great, I think that  would be a great help for a beginner to understand the whole picture.

Regards.

cc @jialez0 @Xynnn007

**Comment by jialez0** [comment]
@chendave At present, the Attestation and KBS systems are still under development. We plan to complete the release of the first version of the whole picture in CoCo v0.5.0 in April this year. Considering this, we have not provided a demo document at present. In CoCo v0.5.0, the deployment and usage of KBS will be included in the CoCo [Quick Start document](https://github.com/confidential-containers/documentation/blob/main/quickstart.md), and we will give the method of using client tool for quick test in README.md of KBS repository.


If you need to conduct a quick end-to-end test on KBS and AS now, you can follow the following steps:

**1. Start KBS:**

```
RUST_LOG=debug ./kbs -s <ip>:<port>
```

Then create a resource file for test and register it to KBS:

```
mkdir test_resources
echo "12345678" > ./test_resources/test
cp --parent test_resources/test /opt/confidential-containers/kbs/repository/default/
```

**2. Use KBS client tool to request resource**

We provide a [KBS client](https://github.com/confidential-containers/kbs/tree/main/tools/client) based on AA to test KBS, you can use it to send request to KBS and perform attestation.

If you want to use `tdx` verifier, you should run this client inside TD guest.
If you want to use `sample` verifier, you should set ENV `export AA_SAMPLE_ATTESTER_TEST=1`.

```
./client --kbs-url http://<ip>:<port> --resource-path default/test_resources/test
```

**Comment by chendave** [comment]
Huge thanks @jialez0 ! will have a try.
