### ISSUE TITLE
GET with payloads are somewhat spooky

### ISSUE THREAD

**Issue by thomas-fossati** [confidential-containers/kbs#4]
GET requests with a payload are unusual and have no defined semantics in HTTP, therefore they come with caveats: see https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.1-6 for the details.  Also see [Veraison challenge-response API](https://github.com/veraison/docs/tree/main/api/challenge-response) for another way to achieve the same goal.

**Comment by jialez0** [comment]
I think we can use `POST` method instead, which will avoid caveat.
