### ISSUE TITLE
JWK public key format definition in KBS Protocol

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#46]
Now we use JWK in a format as defined in https://github.com/confidential-containers/kbs/blob/main/docs/kbs_attestation_protocol.md#public-key
```json
{
    "kty": "$key_type",
    "alg": "$key_algorithm",
    "k": "public_key"
}
```

However the JWK defined in RFC7517 https://www.rfc-editor.org/rfc/rfc7517# does not have the field k.

Now we use [RSA pkcs1v15 padding / key length = 2048bit as the public algorithm](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/cc_kbc/crypto/mod.rs#L16). To follow the RFC it might look like the following?
```
{
    "kty": "RSA", // https://www.rfc-editor.org/rfc/rfc7518#section-6.1
    "alg": "RS256", // https://www.rfc-editor.org/rfc/rfc7518#section-3.1
    "n": "<base64-encoded n parameter in RSA public key>" // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.1
    "e": "<base64-encoded e parameter in RSA public key>" // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.2
}
```

although it is still not a problem as AA & AS logic are all controlled by us so it can pass CI, we should think about "normalize" the definition (including the key type selection) after v0.5.0? cc @sameo @jialez0

**Comment by sameo** [comment]
Hi @Xynnn007, thanks for starting the discussion:

> Now we use JWK in a format as defined in https://github.com/confidential-containers/kbs/blob/main/docs/kbs_attestation_protocol.md#public-key
> 
> ```json
> {
>     "kty": "$key_type",
>     "alg": "$key_algorithm",
>     "k": "public_key"
> }
> ```
> 
> However the JWK defined in RFC7517 https://www.rfc-editor.org/rfc/rfc7517# does not have the field k.
> 

RFC7517 allows for key type specific and even custom fields to be present in the JSON payload:

```
   In addition to the common parameters, each JWK will have members that
   are key type specific.  These members represent the parameters of the
   key.  [Section 6](https://www.rfc-editor.org/rfc/rfc7517#section-6) of the 
   JSON Web Algorithms ([JWA](https://www.rfc-editor.org/rfc/rfc7517#ref-JWA)) [JWA] specification
   defines multiple kinds of cryptographic keys and their associated
   members.
```
and 

```
Additional members can be present in the JWK; if not understood by
   implementations encountering them, they MUST be ignored.  Member
   names used for representing key parameters for different keys types
   need not be distinct.  Any new member name should either be
   registered in the IANA "JSON Web Key Parameters" registry established
   by [Section 8.1](https://www.rfc-editor.org/rfc/rfc7517#section-8.1) or be a value that contains a Collision-Resistant
   Name.
```

and `k` is an accepted value as described in https://www.rfc-editor.org/rfc/rfc7517#appendix-A.3 (Although this is for a symetric key).

> Now we use [RSA pkcs1v15 padding / key length = 2048bit as the public algorithm](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/cc_kbc/crypto/mod.rs#L16). To follow the RFC it might look like the following?
> 
> ```
> {
>     "kty": "RSA", // https://www.rfc-editor.org/rfc/rfc7518#section-6.1
>     "alg": "RS256", // https://www.rfc-editor.org/rfc/rfc7518#section-3.1
>     "n": "<base64-encoded n parameter in RSA public key>" // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.1
>     "e": "<base64-encoded e parameter in RSA public key>" // https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.2
> }
> ```
> 
> although it is still not a problem as AA & AS logic are all controlled by us so it can pass CI, we should think about "normalize" the definition (including the key type selection) after v0.5.0? cc @sameo @jialez0

I agree we should have a normalize definition. The current one is not precise but allows for flexibility in the key type and algorithm choices.
Sticking to RSA means we only support that kind of algorithm for our public key. Hence the generic `k` field to represent the public key and leave it to the implementers to interpret it, thanks to the `kty` and `alg` fields.

RSA is definitely a wise algorithm choice for PKI, but is it the only one we want to support? if that's the case, then your proposed scheme is the [right one](https://www.rfc-editor.org/rfc/rfc7518.html#section-6.3).

**Comment by Xynnn007** [comment]
Thanks a lot for the detailed explaination @sameo ! Although the `k` field still seems a little confusing to me as RFC takes a symmetric key example for this, I'm ok with the current implementation.

FYI Rust supplies a JWK crate for different key types (rsa, ec, ..) https://docs.rs/jsonwebtoken/8.2.0/jsonwebtoken/jwk/struct.Jwk.html if we want to support different pubkey types. : ) and if needed we can make some changes
