### ISSUE TITLE
Integration Key generation, image encryption, Key registration into KBS

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#49]
#### Background
Now to generate a encrypted image for CoCo is not easy, because we need to do the following steps manually:
- Set up CoCo-Keyprovider
- Generate a KEK manually
- Use `skopeo` to encrypt an image using the KEK
- Set up a KBS
- Register the KEK into KBS

Although we can document this, it still makes trouble to newers.

#### What this issue wants?
I suggest integrate CoCo keyprovider into the "cluster of KBS" (in the `docker-compose`) and do some change. The changes include including key generation inside CoCo keyprovider, letting CoCo keyprovider automatically connect to the KBS to register the Key. then a user will do the things above as following
- Set up a "KBS cluster" using `docker-compose`
- Use skopeo to encrypt a image.

Much easier for a user, right?

#### What we need to do?
If we agree with this, here are the following work to be done:
- [ ] Finish `docker-compose.yaml` for "KBS cluster" (including KBS, RVPS and probably AS)
https://github.com/confidential-containers/kbs/pull/43
- [x] Finish resource registration API for KBS
https://github.com/confidential-containers/kbs/pull/30
- [x] Add a launch option for CoCo Keyprovider to connect to a KBS
https://github.com/confidential-containers/attestation-agent/issues/153
- [x] Add dockerfile for CoCo Keyprovider
https://github.com/confidential-containers/attestation-agent/issues/154
- [ ] Integrate CoCo Keyprovider to the "family" of KBS's `docker-compose.yaml`

cc @sameo @fitzthum @bpradipt @jialez0

**Comment by bpradipt** [comment]
@Xynnn007 nice :) . 
May I also suggest to add a Kubernetes manifest file (yaml) to deploy the components. This will make it easier for CI and also for users starting with our quickstart guides. This might help - https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

**Comment by Xynnn007** [comment]
@bpradipt Great suggestion! When we finish the `docker-compose` things, we can start with this.
