### ISSUE TITLE
Failded to compile KBS

### ISSUE THREAD

**Issue by yaoxin1995** [confidential-containers/kbs#52]
Hey, I got following error when I was trying to compile the project:

```
yaoxin@master:~/kbs$ make kbs
Makefile:7: warning: overriding recipe for target 'kbs'
Makefile:3: warning: ignoring old recipe for target 'kbs'
cargo build --no-default-features --features native-as
warning: /home/yaoxin/kbs/src/api_server/Cargo.toml: dependency (tempfile) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
warning: /home/yaoxin/kbs/src/api_server/Cargo.toml: unused manifest key: dev-dependencies.tempfile.dev-workspace
warning: /home/yaoxin/kbs/Cargo.toml: unused manifest key: workspace.dev-dependencies
warning: skipping duplicate package `app` found at `/home/yaoxin/.cargo/git/checkouts/sgxdatacenterattestationprimitives-d6934a418e6beae0/85cf8bd/SampleCode/RustTDQuoteGenerationSample`
   Compiling attestation-service v0.1.0 (https://github.com/confidential-containers/attestation-service.git?rev=9484f06#9484f06f)
   Compiling actix-web-httpauth v0.8.0
error: failed to run custom build command for `attestation-service v0.1.0 (https://github.com/confidential-containers/attestation-service.git?rev=9484f06#9484f06f)`

Caused by:
  process didn't exit successfully: `/home/yaoxin/kbs/target/debug/build/attestation-service-05826db9cb0747e6/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=/home/yaoxin/kbs/target/debug/build/attestation-service-f8d89eef70b8cda2/out
  cargo:rustc-link-search=native=/home/yaoxin/kbs/target/debug/build/attestation-service-f8d89eef70b8cda2/out
  cargo:rustc-link-lib=static=cgo

  --- stderr
  ERROR: build github.com/open-policy-agent/opa/capabilities: cannot load github.com/open-policy-agent/opa/capabilities: no Go source files

warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:7: kbs] Error 101
```

Could someone help me to resolve this error? 

Many thanks

**Comment by yaoxin1995** [comment]
I resolved the error by installing Go from `https://go.dev/doc/install`

**Comment by jialez0** [comment]
Hi @yaoxin1995 , here are two possible solutions:

1. Perhaps you can try updating the Golang version in your environment. In our CI testing environment, we are using the 1.20 version of Golang:
```shell
wget https://go.dev/dl/go1.20.1.linux-amd64.tar.gz && \
tar -C /usr/local -xzf go1.20.1.linux-amd64.tar.gz
export PATH="/usr/local/go/bin:${PATH}"
```

2. You can use the dockerfile provided to compile kbs, which will avoid environmental issues:
```shell
cd kbs
DOCKER_BUILDKIT=1 docker build -t kbs:native-as . -f docker/Dockerfile
```
Then start kbs in docker container:
```
docker run -it --name=kbs --net host kbs:native-as kbs -s <IP>:<PORT>
```

**Comment by yaoxin1995** [comment]
> Hi @yaoxin1995 , here are two possible solutions:
> 
> 1. Perhaps you can try updating the Golang version in your environment. In our CI testing environment, we are using the 1.20 version of Golang:
> 
> ```shell
> wget https://go.dev/dl/go1.20.1.linux-amd64.tar.gz && \
> tar -C /usr/local -xzf go1.20.1.linux-amd64.tar.gz
> export PATH="/usr/local/go/bin:${PATH}"
> ```
> 
> 2. You can use the dockerfile provided to compile kbs, which will avoid environmental issues:
> 
> ```shell
> cd kbs
> DOCKER_BUILDKIT=1 docker build -t kbs:native-as . -f docker/Dockerfile
> ```
> 
> Then start kbs in docker container:
> 
> ```
> docker run -it --name=kbs --net host kbs:native-as kbs -s <IP>:<PORT>
> ```

Many thanks, after changing the golang version, I was able to compile the project, many thanks
