### ISSUE TITLE
Unable to use client tool with http after addition of https support

### ISSUE THREAD

**Issue by Alex-Carter01** [confidential-containers/kbs#55]
I have the Kbs running on the host, it was started with.
`sudo ./kbs --insecure-http -s 0.0.0.0:44444`

I then exec-ed into the kata runtime to try to debug. I had built an initrd that included the client tool for testing. I tried following [the docs](https://github.com/confidential-containers/kbs/tree/main/tools/client) by specifying the URI as such:
`./client --resource-uri kbs://127.0.0.1:8080/a/b/c`
(I have substituted in the system's IP and port, but the error remains the same)

Getting 
`Error: builder error: relative URL without a base`

Am I specifying the resource uri information for the client wrong after the new changes for https?

**Comment by jialez0** [comment]
@Alex-Carter01 BTW, now we need to specify `aa_kbc_params=cc_kbc::http://<ip>:<port>` in agent config :-)

**Comment by Alex-Carter01** [comment]
Thank you! I will add http to the kernel params, and it looks like  
`./client --resource-uri kbs://http://127.0.0.1:8080/a/b/c`
errors with
`Error: download confidential resource: invalid kbs resource uri, should be kbs://<addr-of-kbs>/<repo>/<type>/<tag>`
but I am working with Tobin and it looks like this is coming the AA, so I will build based off a newer version and see if that fixes it. :)
