### ISSUE TITLE
Modify documentation to track "reference-kbs"

### ISSUE THREAD

**Issue by c3d** [confidential-containers/kbs#7]
@slp (@virtee) has begun a [reference implementation](https://github.com/slp/reference-kbs) of the KBS, which as far as I can tell has interesting extensions, notably a way to [register workloads](https://github.com/slp/reference-kbs/blob/main/src/main.rs#L147) which is quite useful in practice.

What is learned from this implementation should probably would need to be integrated in the documentation.

**Comment by jialez0** [comment]
Looks great!  @slp 's word is a significant progress in the KBS project, maybe some of them can become the PR of KBS repository (It has been silent for a long time:))? We can jointly build KBS and make it more practical.

By the way, @sameo mentioned in #3  that will update the KBS protocol document, how is it going?

**Comment by jialez0** [comment]
@slp @sameo @c3d I think workload ID can be used as a special type of measurement value name, which is compatible with the AS verification scheme we currently envision. It should not be passed in the Request, but should be passed in the `tee evidence` in the evidence payload. It has the same status as the original measurement value name of component granularity, and does not need to change our existing protocol to support it.

For convenience of explanation, we assume that for a certain attester/verifier driver, the format of `tee evidence` in the evidence payload is as follows:

```json
{
  "tee-pubkey": "$tee-pubkey",
  "tee-evidence": {
    "measurements": {},
    "tee-report": "$tee-report"
  }
}
```

- If the user chooses not to use workload ID, the evidence payload is as follows:

```json
{
  "tee-pubkey": "$tee-pubkey",
  "tee-evidence": {
    "measurements": {
      "kernel":"1123abc",
      "firmware":"22334bca",
      "agent":"2211cba",
    },
    "tee-report": "$tee-report"
  }
}
```

In this case, AS will obtain and cache all the latest trusted mesurement values of each component of the confidential containers from the software supply chain security architecture for CC (we are planning to build). At this time, the reference value list in AS is as follows:

```json
{
  "kernel":["1123abc", "1142bca"],
  "firmware":["22334bca", "4456bac", "3344ddf"],
  "agent":"["2211cba", "1122gfd"],
  ...
}
```

The user can configure AS to make different decisions according to the matching of measurement values of each component, so as to give different permissions to the verified object.

- If the user chooses to use workload ID, the evidence payload is as follows:

```json
{
  "tee-pubkey": "$tee-pubkey",
  "tee-evidence": {
    "measurements": {
      "$(workload_id)": "$(workload_hash)"
    },
    "tee-report": "$tee-report"
  }
}
```

In this case, the user needs to configure AS and register his workload ID in the reference value list of AS. At this time, the reference value list in AS is as follows:

```json
{
  "$(workload_id)": "$(workload_hash)",
  "$(workload_id_1)": "$(workload_hash_1)",
  "$(workload_id_2)": "$(workload_hash_2)",
  ...
  "kernel":["1123abc", "1142bca"],
  "firmware":["22334bca", "4456bac", "3344ddf"],
  "agent":"["2211cba", "1122gfd"],
  ...
}
```

During verification, AS can select which reference value should be used for comparison verification with workload id.

**Comment by ariel-adam** [comment]
@c3d is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by fitzthum** [comment]
See #13 and the discussion on #12

**Comment by c3d** [comment]
@ariel-adam Still relevant IMO.
