### ISSUE TITLE
Alpha release for v0.6.0

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#96]
We now need a CoCo-published test image.  Thus a alpha release is needed to be cut, which will automatically trigger the CI to build an image.

**Comment by surajssd** [comment]
@Xynnn007 We can avoid doing release by adding support to build images on each merge?

**Comment by Xynnn007** [comment]
Each merge would be too frequent, as some merges are just a little fix. What about a manually triggered action?

**Comment by surajssd** [comment]
So in CAA we build image on each merge. Each build is tagged with a `latest` tag and one that showcases the commit.

And then we can also do tags per release as well. But having on each merge is not too much. That way people get an image on whichever commit they want. It is the least friction way to get people to use the stuff we build.
